In [5]:
# Problem Statement

#This file is a sample of 1000 sales transactions for the Expeditioner. For each sale, there is a row recording when it was sold, 
#where it was sold, what was sold, how it was sold, the quantity sold, and the sales revenue.

#a) What was the value of catalog sales for London in the first quarter?
#b) What percent of the total annual sales were Tokyo Web sales in the fourth quarter?
#c) What percent of Sydney's annual sales was its Catalog sales?
#d) What was the value of catalog sales for London in January and give details of the transactions?
#e) What was the value of Camel saddle sales for Paris in 2002 by quarter?
#f) How many Elephant polo sticks were sold in New York in each month of 2002?

SyntaxError: unexpected EOF while parsing (<ipython-input-5-d36e0e8383f4>, line 12)

In [2]:
import pandas as pd
import numpy as np
#import datetime as dt

df = pd.read_excel("exped.xls")
df.head()

,Transid,WHEN,WHERE,WHAT,HOW,QUANTITY,REVENUE
0,1,2002-11-30,Paris,Exploring in 10 Easy Lessons,Store,4,80
1,2,2002-10-20,London,Camel saddle,Catalog,3,1794
2,3,2002-11-07,Paris,Compass,Store,2,16
3,4,2002-07-28,London,Geo positioning system,Store,3,885
4,5,2002-08-05,Paris,Hammock,Store,3,165

In [3]:
df.sort_values(['WHEN', "HOW"], ascending=[True, True], inplace=True)
df

,Transid,WHEN,WHERE,WHAT,HOW,QUANTITY,REVENUE
114,115,2002-01-03,London,Exploring in 10 Easy Lessons,Store,1,20
747,748,2002-01-05,Paris,Map case,Store,2,30
132,133,2002-01-06,Paris,Hammock,Store,1,55
321,322,2002-01-06,London,Elephant polo stick,Store,1,352
662,663,2002-01-06,Tokyo,How to Win Foreign Friends,Store,4,104
93,94,2002-01-07,Paris,How to Win Foreign Friends,Store,2,52
236,237,2002-01-07,London,Map case,Store,2,30
337,338,2002-01-08,London,Hammock,Store,2,110
630,631,2002-01-08,London,Elephant polo stick,Store,4,1408
732,733,2002-01-08,Paris,Hat - polar explorer,Web,1,34
113,114,2002-01-09,London,Hat - polar explorer,Catalog,4,136
276,277,2002-01-09,London,Hammock,Catalog,5,275
40,41,2002-01-09,Paris,Hammock,Store,4,220
116,117,2002-01-10,London,Hat - polar explorer,Store,4,136
484,485,2002-01-10,Paris,Elephant polo stick,Store,4,1408
212,213,2002-01-11,London,Map case,Store,4,60
701,702,2002-01-11,London,Map case,Web,1,15
442,443,2002-01-12,New York,Exploring in 10 Easy Lessons,Store,1,20
573,574,2002-01-12,New York,Camel saddle,Store,4,2392
829,830,2002-01-12,Paris,How to Win Foreign Friends,Store,2,52
203,204,2002-01-13,Paris,How to Win Foreign Friends,Store,4,104
237,238,2002-01-13,New York,Hat - polar explorer,Web,4,136
209,210,2002-01-14,Tokyo,Camel saddle,Catalog,3,1794
221,222,2002-01-14,Tokyo,Geo positioning system,Store,4,1180
343,344,2002-01-15,New York,Compass,Catalog,3,24
150,151,2002-01-15,London,Geo positioning system,Store,1,295
777,778,2002-01-16,Tokyo,How to Win Foreign Friends,Catalog,3,78
665,666,2002-01-16,London,Boots - snakeproof,Store,5,475
848,849,2002-01-16,London,Elephant polo stick,Store,4,1408
906,907,2002-01-16,London,Elephant polo stick,Store,3,1056
...,...,...,...,...,...,...,...
960,961,2002-12-22,New York,Map case,Catalog,2,30
664,665,2002-12-22,Tokyo,Geo positioning system,Store,5,1475
786,787,2002-12-22,Sydney,Exploring in 10 Easy Lessons,Store,4,80
69,70,2002-12-23,New York,Hammock,Store,2,110
235,236,2002-12-23,London,Boots - snakeproof,Store,2,190
565,566,2002-12-23,Tokyo,Elephant polo stick,Store,4,1408
441,442,2002-12-24,London,How to Win Foreign Friends,Catalog,4,104
546,547,2002-12-24,London,Elephant polo stick,Store,1,352
726,727,2002-12-25,London,Hammock,Catalog,3,165
560,561,2002-12-25,Paris,Elephant polo stick,Store,4,1408
926,927,2002-12-25,London,Camel saddle,Store,5,2990
966,967,2002-12-26,Sydney,Compass,Catalog,3,24
901,902,2002-12-26,London,Hammock,Store,4,220
297,298,2002-12-28,Tokyo,Geo positioning system,Catalog,4,1180
363,364,2002-12-28,London,Hammock,Catalog,2,110
260,261,2002-12-28,Paris,Compass,Store,3,24
566,567,2002-12-28,London,Compass,Store,2,16
567,568,2002-12-28,New York,Compass,Store,3,24
894,895,2002-12-28,Tokyo,Elephant polo stick,Store,2,704
462,463,2002-12-28,New York,Exploring in 10 Easy Lessons,Web,5,100
623,624,2002-12-28,London,Boots - snakeproof,Web,1,95
825,826,2002-12-29,Tokyo,Map case,Catalog,4,60
206,207,2002-12-29,New York,Camel saddle,Store,1,598
266,267,2002-12-29,New York,Elephant polo stick,Store,2,704
574,575,2002-12-29,Paris,Hat - polar explorer,Store,4,136
633,634,2002-12-29,London,How to Win Foreign Friends,Store,3,78
939,940,2002-12-29,Tokyo,Exploring in 10 Easy Lessons,Store,4,80
214,215,2002-12-30,London,Hammock,Store,2,110
220,221,2002-12-31,London,Hammock,Catalog,4,220
879,880,2002-12-31,Paris,Exploring in 10 Easy Lessons,Store,3,60

In [4]:
#def get_qrtr(datevalue):
#    if ((datevalue >= dt.date('2002-01-01')) & (datevalue <= dt.date('2002-03-31'))):
#        return 1
#    if ((datevalue >= dt.date('2002-04-01')) & (datevalue <= dt.date('2002-06-31'))):
#        return 2
#    if ((datevalue >= dt.date('2002-07-01')) & (datevalue <= dt.date('2002-09-31'))):
#        return 3
#    if ((datevalue >= dt.date('2002-10-01')) & (datevalue <= dt.date('2002-12-31'))):
#        return 4

df['MNTH'] = df['WHEN'].datetime.month
df['YR'] = df['WHEN'].datetime.year
df['QRTR'] = df['WHEN'].datetime.quarter

def get_qrtr(monthvalue):
    if ((monthvalue >= 1) & (monthvalue <= 3)):
        return 1
    if ((monthvalue >= 4) & (monthvalue <= 6)):
        return 2
    if ((monthvalue >= 7) & (monthvalue <= 9)):
        return 3
    if ((monthvalue >= 10) & (monthvalue <= 12)):
        return 4

df['QRTR1'] = df['MNTH'].apply(get_qrtr)

df

,Transid,WHEN,WHERE,WHAT,HOW,QUANTITY,REVENUE,MNTH,YR,QRTR,QRTR1
114,115,2002-01-03,London,Exploring in 10 Easy Lessons,Store,1,20,1,2002,1,1
747,748,2002-01-05,Paris,Map case,Store,2,30,1,2002,1,1
132,133,2002-01-06,Paris,Hammock,Store,1,55,1,2002,1,1
321,322,2002-01-06,London,Elephant polo stick,Store,1,352,1,2002,1,1
662,663,2002-01-06,Tokyo,How to Win Foreign Friends,Store,4,104,1,2002,1,1
93,94,2002-01-07,Paris,How to Win Foreign Friends,Store,2,52,1,2002,1,1
236,237,2002-01-07,London,Map case,Store,2,30,1,2002,1,1
337,338,2002-01-08,London,Hammock,Store,2,110,1,2002,1,1
630,631,2002-01-08,London,Elephant polo stick,Store,4,1408,1,2002,1,1
732,733,2002-01-08,Paris,Hat - polar explorer,Web,1,34,1,2002,1,1
113,114,2002-01-09,London,Hat - polar explorer,Catalog,4,136,1,2002,1,1
276,277,2002-01-09,London,Hammock,Catalog,5,275,1,2002,1,1
40,41,2002-01-09,Paris,Hammock,Store,4,220,1,2002,1,1
116,117,2002-01-10,London,Hat - polar explorer,Store,4,136,1,2002,1,1
484,485,2002-01-10,Paris,Elephant polo stick,Store,4,1408,1,2002,1,1
212,213,2002-01-11,London,Map case,Store,4,60,1,2002,1,1
701,702,2002-01-11,London,Map case,Web,1,15,1,2002,1,1
442,443,2002-01-12,New York,Exploring in 10 Easy Lessons,Store,1,20,1,2002,1,1
573,574,2002-01-12,New York,Camel saddle,Store,4,2392,1,2002,1,1
829,830,2002-01-12,Paris,How to Win Foreign Friends,Store,2,52,1,2002,1,1
203,204,2002-01-13,Paris,How to Win Foreign Friends,Store,4,104,1,2002,1,1
237,238,2002-01-13,New York,Hat - polar explorer,Web,4,136,1,2002,1,1
209,210,2002-01-14,Tokyo,Camel saddle,Catalog,3,1794,1,2002,1,1
221,222,2002-01-14,Tokyo,Geo positioning system,Store,4,1180,1,2002,1,1
343,344,2002-01-15,New York,Compass,Catalog,3,24,1,2002,1,1
150,151,2002-01-15,London,Geo positioning system,Store,1,295,1,2002,1,1
777,778,2002-01-16,Tokyo,How to Win Foreign Friends,Catalog,3,78,1,2002,1,1
665,666,2002-01-16,London,Boots - snakeproof,Store,5,475,1,2002,1,1
848,849,2002-01-16,London,Elephant polo stick,Store,4,1408,1,2002,1,1
906,907,2002-01-16,London,Elephant polo stick,Store,3,1056,1,2002,1,1
...,...,...,...,...,...,...,...,...,...,...,...
960,961,2002-12-22,New York,Map case,Catalog,2,30,12,2002,4,4
664,665,2002-12-22,Tokyo,Geo positioning system,Store,5,1475,12,2002,4,4
786,787,2002-12-22,Sydney,Exploring in 10 Easy Lessons,Store,4,80,12,2002,4,4
69,70,2002-12-23,New York,Hammock,Store,2,110,12,2002,4,4
235,236,2002-12-23,London,Boots - snakeproof,Store,2,190,12,2002,4,4
565,566,2002-12-23,Tokyo,Elephant polo stick,Store,4,1408,12,2002,4,4
441,442,2002-12-24,London,How to Win Foreign Friends,Catalog,4,104,12,2002,4,4
546,547,2002-12-24,London,Elephant polo stick,Store,1,352,12,2002,4,4
726,727,2002-12-25,London,Hammock,Catalog,3,165,12,2002,4,4
560,561,2002-12-25,Paris,Elephant polo stick,Store,4,1408,12,2002,4,4
926,927,2002-12-25,London,Camel saddle,Store,5,2990,12,2002,4,4
966,967,2002-12-26,Sydney,Compass,Catalog,3,24,12,2002,4,4
901,902,2002-12-26,London,Hammock,Store,4,220,12,2002,4,4
297,298,2002-12-28,Tokyo,Geo positioning system,Catalog,4,1180,12,2002,4,4
363,364,2002-12-28,London,Hammock,Catalog,2,110,12,2002,4,4
260,261,2002-12-28,Paris,Compass,Store,3,24,12,2002,4,4
566,567,2002-12-28,London,Compass,Store,2,16,12,2002,4,4
567,568,2002-12-28,New York,Compass,Store,3,24,12,2002,4,4
894,895,2002-12-28,Tokyo,Elephant polo stick,Store,2,704,12,2002,4,4
462,463,2002-12-28,New York,Exploring in 10 Easy Lessons,Web,5,100,12,2002,4,4
623,624,2002-12-28,London,Boots - snakeproof,Web,1,95,12,2002,4,4
825,826,2002-12-29,Tokyo,Map case,Catalog,4,60,12,2002,4,4
206,207,2002-12-29,New York,Camel saddle,Store,1,598,12,2002,4,4
266,267,2002-12-29,New York,Elephant polo stick,Store,2,704,12,2002,4,4
574,575,2002-12-29,Paris,Hat - polar explorer,Store,4,136,12,2002,4,4
633,634,2002-12-29,London,How to Win Foreign Friends,Store,3,78,12,2002,4,4
939,940,2002-12-29,Tokyo,Exploring in 10 Easy Lessons,Store,4,80,12,2002,4,4
214,215,2002-12-30,London,Hammock,Store,2,110,12,2002,4,4
220,221,2002-12-31,London,Hammock,Catalog,4,220,12,2002,4,4
879,880,2002-12-31,Paris,Exploring in 10 Easy Lessons,Store,3,60,12,2002,4,4

In [ ]:
pd.pivot_table(df, index= ['Region', score], values= "REVENUE", aggfunc= 'count',
              fill_value= 0)